# Generated by Django 3.2.7 on 2021-09-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210903_1610'),
        ('store', '0005_auto_20210903_1804'),
    ]

    operations = [
    ]
