# Generated by Django 3.2.7 on 2021-09-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_0005_auto_20210903_1610_0005_auto_20210903_1804'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
